es3 : stack.o main.o item-string.o 
	gcc stack.o item-string.o main.o -o es3.exe
	
stack.o :
	gcc -c stack.c
	
main.o :
	gcc -c main.c
	
item-string.o :
	gcc -c item-string.c
	
clean: 
	rm -rf  *.o *.exe
