link: auto.o concessionario.o item_auto.o list.o main.o
	gcc auto.o concessionario.o item_auto.o list.o main.o -o main.exe

auto.o:
	gcc -c auto.c

concessionario.o:
	gcc -c concessionario.c

item_auto.o:
	gcc -c item_auto.c

list.o:
	gcc -c list.c

main.o:
	gcc -c main.c

clean:
	rm -f *.o *.exe