/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-01 14:53:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import model.ProdottoBean;
import java.util.List;

public final class homePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("model.ProdottoBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");

    List<ProdottoBean> prodottiCasuali = (List<ProdottoBean>) request.getSession().getAttribute("randomProdotti");

      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"meta description\">\r\n");
      out.write("\r\n");
      out.write("    <title>G&G Jewelry</title> \r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/logo.png\" type=\"image/x-icon\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--== Google Fonts ==-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--=== Bootstrap CSS ===--> \r\n");
      out.write("    <link href=\"assets/css/vendor/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Font-Awesome CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/vendor/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Plugins CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Main Style CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Modernizer JS -->\r\n");
      out.write("    <script src=\"assets/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragments/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--== Banner // Slider Area Start ==-->\r\n");
      out.write("<section id=\"banner-area\">\r\n");
      out.write("    <div class=\"ruby-container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <div id=\"banner-carousel\" class=\"owl-carousel\">\r\n");
      out.write("                    <!-- Banner Single Carousel Start -->\r\n");
      out.write("                    <div class=\"single-carousel-wrap slide-item-1\">\r\n");
      out.write("                        <div class=\"banner-caption text-center text-lg-left\">\r\n");
      out.write("                            <h4>G&G Jewelry</h4>\r\n");
      out.write("                            <h3>Presto fuori!!</h3>\r\n");
      out.write("                            <h2>Anello Angel</h2>\r\n");
      out.write("                            <p>L'anello \"Anello Angel\" è un'opera d'arte. Realizzato in oro bianco 18 carati, il suo design elegante incornicia una splendida pietra centrale. </p>\r\n");
      out.write("                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Banner Single Carousel End -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Banner Single Carousel Start -->\r\n");
      out.write("                    <div class=\"single-carousel-wrap slide-item-2\">\r\n");
      out.write("                        <div class=\"banner-caption text-center text-lg-left\">\r\n");
      out.write("                            <h4>Nuova Collezione 2024</h4>\r\n");
      out.write("                            <h3>Presto fuori!!</h3>\r\n");
      out.write("                            <h2>Collana boreale</h2>\r\n");
      out.write("                            <p>Il set collana \"boreale\" è una creazione raffinata e incantevole, ideale per illuminare ogni occasione speciale</p>\r\n");
      out.write("                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Banner Single Carousel End -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--== Banner Slider End ==-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--== New Collection Area Start ==-->\r\n");
      out.write("<section id=\"new-collection-area\" class=\"p-9\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                <div class=\"section-title\">\r\n");
      out.write("                    <h2>Nuova Collezione di prodotti</h2>\r\n");
      out.write("                    <p>Prodotti in Saldo.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <div class=\"new-collection-tabs\">\r\n");
      out.write("                    <div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("                        <div class=\"tab-pane fade show active\" id=\"feature-products\" role=\"tabpanel\" aria-labelledby=\"feature-products-tab\">\r\n");
      out.write("                            <div class=\"products-wrapper\">\r\n");
      out.write("                                <div class=\"products-carousel owl-carousel\">\r\n");
      out.write("                                    ");
 for (ProdottoBean prodotto : prodottiCasuali) { 
      out.write("\r\n");
      out.write("                                    <!-- Loop through the randomProducts stored in session -->\r\n");
      out.write("                                    <div class=\"single-product-item text-center\">\r\n");
      out.write("                                        <figure class=\"product-thumb\">\r\n");
      out.write("                                            <a href=\"DettaglioProdotto?id=");
      out.print( prodotto.getId() );
      out.write("\">\r\n");
      out.write("                                                <img src=\"");
      out.print( prodotto.getImmagine() );
      out.write("\" alt=\"");
      out.print( prodotto.getNome() );
      out.write("\" class=\"img-fluid\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </figure>\r\n");
      out.write("                                        <div class=\"product-details\">\r\n");
      out.write("                                            <h2><a href=\"DettaglioProdotto?id=");
      out.print( prodotto.getId() );
      out.write('"');
      out.write('>');
      out.print( prodotto.getNome() );
      out.write("</a></h2>\r\n");
      out.write("                                            <span class=\"price\">$");
      out.print( prodotto.getCosto() );
      out.write("</span>\r\n");
      out.write("                                            \r\n");
      out.write("	                                         ");

                                            if(request.getSession().getAttribute("admin") == Boolean.TRUE) {
                                            
      out.write("       	\r\n");
      out.write("                                            	<button class=\"btn-add-to-cart\" onclick=\"window.location.href='modificaProdotto?mode=modifica&prodotto=");
      out.print( prodotto.getId() );
      out.write("'\">Modifica prodotto</button>\r\n");
      out.write("                                            ");
 
                                            } 
                                            else 
                                            {
                                                if(request.getSession().getAttribute("logged") != null) 
                                                {
                                                
                                                    if(prodotto.getQuantita() != 0) 
                                                    {
                                                    
      out.write("\r\n");
      out.write("                                                    <button class=\"btn-add-to-cart\" onclick=\"addToCart('");
 out.print(prodotto.getId()); 
      out.write("')\" value=\"Acquista\">Acquista</button>\r\n");
      out.write("                                                	");
 
                                                    } 
                                                    else 
                                                    { 
                                                    
      out.write("\r\n");
      out.write("                                                        <button class=\"btn-add-to-cart\" value=\"Acquista\">Esaurito</button>\r\n");
      out.write("                                                	");

                                                    }
                                                }   
                                                else 
                                                    {
                                                    if(prodotto.getQuantita() != 0) {
                                                    
      out.write("   \r\n");
      out.write("                                                        <button class=\"btn-add-to-cart\" onclick=\"window.location.href='loginPage.jsp'\" value=\"Acquista\">Accedi per acquistare</button>\r\n");
      out.write("                                                    ");
 
                                                    } 
                                                    else { 
                                                    
      out.write("\r\n");
      out.write("                                                        <button class=\"btn-add-to-cart\" value=\"Acquista\">Esaurito</button>\r\n");
      out.write("                                                    ");

                                                    }
                                                }	
                                            }
                                            
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!--== About Us Area Start ==-->\r\n");
      out.write("<section id=\"aboutUs-area\" class=\"pt-9\">\r\n");
      out.write("    <div class=\"ruby-container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <!-- About Image Area Start -->\r\n");
      out.write("                <div class=\"about-image-wrap\">\r\n");
      out.write("                    <a href=\"about.html\"><img src=\"assets/img/about-img.png\" alt=\"About Us\" class=\"img-fluid\"/></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Image Area End -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("                <!-- About Text Area Start -->\r\n");
      out.write("                <div class=\"about-content-wrap ml-0 ml-lg-5 mt-5 mt-lg-0\">\r\n");
      out.write("                    <h2>Chi siamo</h2>\r\n");
      out.write("                    <h3>SIAMO VISIONARI</h3>\r\n");
      out.write("                    <div class=\"about-text\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Benvenuti da G&G Jewelry, dove l'arte della gioielleria prende vita. Da anni siamo specializzati nella creazione e vendita di gioielli unici \r\n");
      out.write("                            e di alta qualità, realizzati con passione e maestria artigianale. Ogni pezzo che trovate nel nostro negozio è una testimonianza del nostro impegno \r\n");
      out.write("                            per l'eccellenza, combinando design innovativi con materiali preziosi. \r\n");
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("                        \r\n");
      out.write("                        <p> \r\n");
      out.write("                            Che siate alla ricerca di un regalo speciale o di un pezzo esclusivo per voi stessi,\r\n");
      out.write("                            da G&G Jewelry troverete un servizio personalizzato e una collezione che incanta e ispira. La nostra missione è trasformare ogni desiderio in realtà, \r\n");
      out.write("                            creando gioielli che raccontano storie e celebrano momenti indimenticabili.\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h4 class=\"vertical-text\">CHI SIAMO?</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Text Area End -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--== About Us Area End ==-->\r\n");
      out.write("\r\n");
      out.write("<!--== New Collection Area End ==-->\r\n");
      out.write("\r\n");
      out.write("<!--== New Collection Area End ==-->\r\n");
      out.write(" \r\n");
      out.write("\n");
      out.write("<!--== Testimonial Area Start ==-->\r\n");
      out.write("<section id=\"testimonial-area\">\r\n");
      out.write("    <div class=\"ruby-container\">\r\n");
      out.write("        <div class=\"testimonial-wrapper\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <!-- Section Title Start -->\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <h2>Le persone cosa pensano di noi</h2>\r\n");
      out.write("                        <p>Feedbacks</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Section Title End -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-7 m-auto text-center\">\r\n");
      out.write("                    <div class=\"testimonial-content-wrap\">\r\n");
      out.write("                        <div id=\"testimonialCarousel\" class=\"owl-carousel\">\r\n");
      out.write("                            <div class=\"single-testimonial-item\">\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    \"Ho recentemente acquistato un anello da G&G Jewelry e non potrei essere più soddisfatto della mia esperienza.\r\n");
      out.write("                                    l'assistentenza è stata estremamente competente e paziente, aiutandomi a trovare il gioiello perfetto per il mio anniversario.\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <h3 class=\"client-name\">Angela Mercanti</h3>\r\n");
      out.write("                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"single-testimonial-item\">\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Consiglio vivamente Eterna Gioielli a chiunque cerchi un gioiello unico e di alta qualità. Non vedo l'ora di tornare per i miei futuri acquisti!\"\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <h3 class=\"client-name\">Maria Boreali</h3>\r\n");
      out.write("                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</section>\r\n");
      out.write("<!--== Testimonial Area End ==-->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragments/footer.jsp", out, false);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- Scroll to Top Start -->\r\n");
      out.write("<a href=\"#\" class=\"scrolltotop\"><i class=\"fa fa-angle-up\"></i></a>\r\n");
      out.write("<!-- Scroll to Top End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--=======================Javascript============================-->\r\n");
      out.write("<!--=== Jquery Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<!--=== Jquery Migrate Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery-migrate-1.4.1.min.js\"></script>\r\n");
      out.write("<!--=== Popper Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/popper.min.js\"></script>\r\n");
      out.write("<!--=== Bootstrap Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("<!--=== Plugins Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("<!--=== Active Js ===-->\r\n");
      out.write("<script src=\"assets/js/active.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/addedToCart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
