/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-01 15:07:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Base64;
import java.util.Base64.Decoder;
import model.UtenteBean;
import model.IndirizzoBean;
import model.IndirizzoDAO;
import model.MetodoDiPagamentoBean;
import model.MetodoDiPagamentoDAO;
import java.sql.SQLException;
import model.OrdineDao;
import model.OrdineBean;
import java.util.List;

public final class memberArea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("model.IndirizzoDAO");
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("java.util.Base64.Decoder");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.OrdineBean");
    _jspx_imports_classes.add("model.MetodoDiPagamentoDAO");
    _jspx_imports_classes.add("model.MetodoDiPagamentoBean");
    _jspx_imports_classes.add("model.IndirizzoBean");
    _jspx_imports_classes.add("model.UtenteBean");
    _jspx_imports_classes.add("model.OrdineDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"meta description\">\r\n");
      out.write("\r\n");
      out.write("    <title>Area utente</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!--=== Favicon ===-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/logo.png\" type=\"image/x-icon\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--== Google Fonts ==-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--=== Bootstrap CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/vendor/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Font-Awesome CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/vendor/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Plugins CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--=== Main Style CSS ===-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Modernizer JS -->\r\n");
      out.write("    <script src=\"assets/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragments/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--== Page Title Area Start ==-->\r\n");
      out.write("<div id=\"page-title-area\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12 text-center\">\r\n");
      out.write("                <div class=\"page-title-content\">\r\n");
      out.write("                    <h1>Area Utente</h1>\r\n");
      out.write("                    <ul class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"homePage.jsp\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"memberArea.jsp\" class=\"active\">Area Utente</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--== Page Title Area End ==-->\r\n");
      out.write("\r\n");
      out.write("<!--== Page Content Wrapper Start ==-->\r\n");
      out.write("<div id=\"page-content-wrapper\" class=\"p-9\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <!-- My Account Page Start -->\r\n");
      out.write("                <div class=\"myaccount-page-wrapper\">\r\n");
      out.write("                    <!-- My Account Tab Menu Start -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-3\">\r\n");
      out.write("                            <div class=\"myaccount-tab-menu nav\" role=\"tablist\">\r\n");
      out.write("                                <a href=\"#dashboad\" class=\"active\" data-toggle=\"tab\"><i class=\"fa fa-dashboard\"></i>\r\n");
      out.write("                                    Area utente</a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"#orders\" data-toggle=\"tab\"><i class=\"fa fa-cart-arrow-down\"></i> Ordini</a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"#address\" data-toggle=\"tab\"><i class=\"fa fa-map-marker\"></i>Indirizzo</a>\r\n");
      out.write("                                \r\n");
      out.write("                                <a href=\"#payment-method\" data-toggle=\"tab\"><i class=\"fa fa-map-marker\"></i>Metodi di Pagamento</a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"#account-info\" data-toggle=\"tab\"><i class=\"fa fa-user\"></i> Informazioni account</a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"LogOutServlet\"><i class=\"fa fa-sign-out\"></i> Logout</a>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- My Account Tab Menu End -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- My Account Tab Content Start -->\r\n");
      out.write("                        <div class=\"col-lg-9 mt-5 mt-lg-0\">\r\n");
      out.write("                            <div class=\"tab-content\" id=\"myaccountContent\">\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("                                <div class=\"tab-pane fade show active\" id=\"dashboad\" role=\"tabpanel\">\r\n");
      out.write("                                    <div class=\"myaccount-content\">\r\n");
      out.write("                                        <h3>Area Utente</h3>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"welcome\">\r\n");
      out.write("                                            <p>");

												Boolean isLoggedIn = (Boolean) session.getAttribute("logged");
										        if (isLoggedIn != null && isLoggedIn) {
										            String nome = (String) session.getAttribute("nome");
										            String cognome = (String) session.getAttribute("cognome");
										            out.println("<p>Bentornato, " + nome + " " + cognome + "!</p>");
										        } else {
										            out.println("<p>Perfavore <a href='loginPage.jsp'>accedi</a> per continuare.</p>");
										        }
										
										        
 												
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <p class=\"mb-0\">Dalla dashboard del tuo account. puoi facilmente controllare e visualizzare il tuo\r\n");
      out.write("                                            ordini recenti, gestisci i tuoi indirizzi di spedizione e fatturazione e modifica i tuoi\r\n");
      out.write("                                            password e dettagli dell'account.\r\n");
      out.write("                                         </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("<div class=\"tab-pane fade\" id=\"orders\" role=\"tabpanel\">\r\n");
      out.write("    <div class=\"myaccount-content\">\r\n");
      out.write("        <h3>I tuoi Ordini</h3>\r\n");
      out.write("        <div class=\"myaccount-table table-responsive text-center\">\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <thead class=\"thead-light\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Data</th>\r\n");
      out.write("                        <th>Costo Totale</th>\r\n");
      out.write("                        <th>Dettagli</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");

                        OrdineDao ordineDAO = new OrdineDao();
                        String userEmail = (String) session.getAttribute("email");
                        List<OrdineBean> ordini = null;

                        if (userEmail != null && !userEmail.isEmpty()) {
                            try {
                                ordini = ordineDAO.doRetrieveByEmail(userEmail);
                            } catch (Exception e) {
                                out.println("Errore: " + e.getMessage());
                            }
                        }

                        if (ordini != null && !ordini.isEmpty()) {
                            for (OrdineBean ordine : ordini) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( ordine.getData() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( ordine.getCostoTotale() );
      out.write("</td>\r\n");
      out.write("                        <td><a href=\"visualizzaOrdine.jsp?id=");
      out.print( ordine.getId());
      out.write("\" class=\"btn-add-to-cart\">Visualizza</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                        } else {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"4\">Nessun ordine trovato per l'email ");
      out.print( userEmail );
      out.write(".</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("<div class=\"tab-pane fade\" id=\"payment-method\" role=\"tabpanel\">\r\n");
      out.write("    <div class=\"myaccount-content\">\r\n");
      out.write("        <h3>I tuoi Metodi di Pagamento</h3>\r\n");
      out.write("		<form action=\"modificaInfo\" method=\"get\">\r\n");
      out.write("	  		<input type=\"hidden\" value=\"");
 out.print(request.getSession().getAttribute("utente"));
      out.write("\" name=\"utente\">\r\n");
      out.write("	  		<input type=\"hidden\" name=\"mode\" value=\"add\">\r\n");
      out.write("	  		<input type=\"hidden\" name=\"target\" value=\"metodoPagamento\">\r\n");
      out.write("	        <button class=\"btn btn-primary mb-3\">Aggiungi Metodo di Pagamento</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"myaccount-table table-responsive text-center\">\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <thead class=\"thead-light\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Tipo</th>\r\n");
      out.write("                        <th>Numero carta</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");

                        MetodoDiPagamentoDAO metodoDiPagamentoDAO = new MetodoDiPagamentoDAO();
                        List<MetodoDiPagamentoBean> metodiDiPagamento = null;

                        if (userEmail != null && !userEmail.isEmpty()) {
                            try {
                                metodiDiPagamento = metodoDiPagamentoDAO.doRetrieveByEmail(userEmail);
                            } catch (Exception e) {
                                out.println("Errore: " + e.getMessage());
                            }
                        }

                        if (metodiDiPagamento != null && !metodiDiPagamento.isEmpty()) {
                            for (MetodoDiPagamentoBean metodo : metodiDiPagamento) {
                            	if(metodo.getTipo().equals("iban")){
                    
      out.write("\r\n");
      out.write("                    <tr></tr>\r\n");
      out.write("                    ");
} else{
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( metodo.getTipo() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( metodo.getNumeroCarta() );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
}
                            }
                        } else {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"3\">Nessun metodo di pagamento trovato per l'email ");
      out.print( userEmail );
      out.write(".</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("                                <!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("<div class=\"tab-pane fade\" id=\"address\" role=\"tabpanel\">\r\n");
      out.write("    <div class=\"myaccount-content\">\r\n");
      out.write("        <h3>I tuoi Indirizzi di Spedizione</h3>\r\n");
      out.write("		<form action=\"modificaInfo\" method=\"get\">\r\n");
      out.write("	  		<input type=\"hidden\" value=\"");
 out.print(request.getSession().getAttribute("utente"));
      out.write("\" name=\"utente\">\r\n");
      out.write("	  		<input type=\"hidden\" name=\"mode\" value=\"add\">\r\n");
      out.write("	  		<input type=\"hidden\" name=\"target\" value=\"indirizzo\">\r\n");
      out.write("	        <button class=\"btn btn-primary mb-3\">Aggiungi Indirizzo</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"myaccount-table table-responsive text-center\">\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <thead class=\"thead-light\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Città</th>\r\n");
      out.write("                        <th>Provincia</th>\r\n");
      out.write("                        <th>CAP</th>\r\n");
      out.write("                        <th>Via</th>\r\n");
      out.write("                        <th>Civico</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");

                        IndirizzoDAO indirizzoDAO = new IndirizzoDAO();
                        List<IndirizzoBean> indirizzi = null;

                        if (userEmail != null && !userEmail.isEmpty()) {
                            try {
                                indirizzi = indirizzoDAO.doRetrieveByEmail(userEmail);
                            } catch (Exception e) {
                                out.println("Errore: " + e.getMessage());
                            }
                        }

                        if (indirizzi != null && !indirizzi.isEmpty()) {
                            for (IndirizzoBean indirizzo : indirizzi) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( indirizzo.getCitta() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( indirizzo.getProvincia() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( indirizzo.getCap() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( indirizzo.getVia() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( indirizzo.getCivico() );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                        } else {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"6\">Nessun indirizzo trovato per l'email ");
      out.print( userEmail );
      out.write(".</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("                                <!-- Single Tab Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Single Tab Content Start -->\r\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"account-info\" role=\"tabpanel\">\r\n");
      out.write("                                    <div class=\"myaccount-content\">\r\n");
      out.write("                                        <h3>Dettagli dell'Account</h3>\r\n");
      out.write("										");

										Decoder decoder = Base64.getDecoder();	
										String encodedPassword = (String)request.getSession().getAttribute("password");
										String decodedPwd = new String(decoder.decode(encodedPassword));
										
      out.write("\r\n");
      out.write("                                        <div class=\"account-details-form\">\r\n");
      out.write("                                            <form action=\"modificaInfo\" id=\"modificaInfo\" method=\"post\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"utente\" value=\"");
      out.print( request.getSession().getAttribute("utente") );
      out.write("\">\r\n");
      out.write("											<input type=\"hidden\" name=\"target\" value=\"utente\">\r\n");
      out.write("											<input type=\"hidden\" name=\"mode\" value=\"update\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                                        <div class=\"single-input-item\">\r\n");
      out.write("                                                            <label for=\"nome\">Nome</label>\r\n");
      out.write("                                                            <input type=\"text\" id=\"nomeNuovo\" name=\"nomeNuovo\"\r\n");
      out.write("                                                                   placeholder=\"Nome\" value=\"");
      out.print( request.getSession().getAttribute("nome") );
      out.write("\"/>\r\n");
      out.write("                                                                   <p  class=\"errors\"  style=\"color:red;\" id=\"error-name\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                                        <div class=\"single-input-item\">\r\n");
      out.write("                                                            <label for=\"cognome\">Cognome</label>\r\n");
      out.write("                                                            <input type=\"text\" id=\"cognomeNuovo\" name=\"cognomeNuovo\" placeholder=\"Cognome\" value=\"");
      out.print( request.getSession().getAttribute("cognome") );
      out.write("\"/>\r\n");
      out.write("                                                        	<p  class=\"errors\"  style=\"color:red;\" id=\"error-surname\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"single-input-item\">\r\n");
      out.write("                                                    <label for=\"username\">Username</label>\r\n");
      out.write("                                                    <input type=\"text\" id=\"usernameNuovo\" name=\"usernameNuovo\" placeholder=\"Username\" value=\"");
      out.print( request.getSession().getAttribute("utente") );
      out.write("\"/>\r\n");
      out.write("                                                	<p  class=\"errors\"  style=\"color:red;\" id=\"error-username\"></p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- <div class=\"single-input-item\">\r\n");
      out.write("                                                    <label for=\"email\">Email</label>\r\n");
      out.write("                                                    <input type=\"email\" id=\"emailNuovo\" name=\"emailNuovo\" placeholder=\"Email\" value=\"");
      out.print( request.getSession().getAttribute("email") );
      out.write("\"/>\r\n");
      out.write("                                                	<p  class=\"errors\"  style=\"color:red;\" id=\"error-email\"></p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                 -->\r\n");
      out.write("\r\n");
      out.write("                                                <fieldset>\r\n");
      out.write("                                                    <legend>Cambio Password</legend>\r\n");
      out.write("                                                    \r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                                            <div class=\"single-input-item\">\r\n");
      out.write("                                                                <label for=\"new-pwd\">\r\n");
      out.write("                                                                    Password</label>\r\n");
      out.write("                                                                <input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("                                                                       placeholder=\"Password\" value=\"");
      out.print( decodedPwd);
      out.write("\"/>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                                            <div class=\"single-input-item\">\r\n");
      out.write("                                                                <label for=\"passwordCheck\">Ripeti\r\n");
      out.write("                                                                    Password</label>\r\n");
      out.write("                                                                <input type=\"password\" id=\"passwordCheck\" name=\"passwordCheck\"\r\n");
      out.write("                                                                       placeholder=\"Ripeti Password\" value=\"");
      out.print( decodedPwd);
      out.write("\"/>\r\n");
      out.write("                                                            	<p  class=\"errors\"  style=\"color:red;\" id=\"error-pwd\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </fieldset>\r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"single-input-item\">\r\n");
      out.write("                                                    <input class=\"btn-login btn-add-to-cart\" type=\"submit\" id=\"modificaInfoBtn\" value=\"Modifica dati\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Single Tab Content End -->\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- My Account Tab Content End -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- My Account Page End -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--== Page Content Wrapper End ==-->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragments/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Scroll to Top Start -->\r\n");
      out.write("<a href=\"#\" class=\"scrolltotop\"><i class=\"fa fa-angle-up\"></i></a>\r\n");
      out.write("<!-- Scroll to Top End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--=======================Javascript============================-->\r\n");
      out.write("<!--=== Jquery Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<!--=== Jquery Migrate Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery-migrate-1.4.1.min.js\"></script>\r\n");
      out.write("<!--=== Popper Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/popper.min.js\"></script>\r\n");
      out.write("<!--=== Bootstrap Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("<!--=== Plugins Min Js ===-->\r\n");
      out.write("<script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--=== Active Js ===-->\r\n");
      out.write("<script src=\"assets/js/active.js\"></script>\r\n");
      out.write("<script src=\"assets/js/aggiornaInfo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
